task_id: calibration_obs_1
feature_of_interest: eytracker calibration
stimulus_id: calibration_task_1
instruction_id: '13'
device_id_array:
- FLIR_blackfly_1
- Eyelink_1
- Mic_Yeti_dev_1
- IPhone_dev_1
arg_parser: iout.stim_param_reader.py::RawTaskParams()
