stimulus_id: intro_cog_task_1
stimulus_description: intro cognition
num_iterations: 1
duration: null
arg_parser: iout.task_param_reader.py::StimulusArgs()
stimulus_file_type: psychopy
stimulus_file: tasks.task.py::Introduction_Task()
prompt: false
