task_id: noIMU_gogogo_obs_1
feature_of_interest: speech
stimulus_id: GoGoGo_task_1
instruction_id: gogo_1
device_id_array:
- Intel_D455_1
- Intel_D455_2
- Intel_D455_3
- Mbient_LH_2
- Mbient_RH_2
- Mbient_RF_2
- Mbient_LF_2
- Mbient_BK_1
- FLIR_blackfly_1
- Eyelink_1
- Mic_Yeti_dev_1
- IPhone_dev_1
arg_parser: iout.stim_param_reader.py::RawTaskParams()
