stimulus_id: progress_bar_2
stimulus_description: progress
num_iterations: 1
duration: 7
arg_parser: iout.stim_param_reader.py::StimulusArgs
stimulus_file_type: psychopy
stimulus_file: tasks.task.py::Task_ShowProgressBar()
slide_image: Part2_Progress_01_23_25.jpg