name: neurobooth-staging
channels:
  - conda-forge
  - defaults
dependencies:
  - asttokens=2.0.5
  - backcall=0.2.0
  - bcrypt=3.2.0
  - blas=1.0
  - blosc=1.21.3
  - bzip2=1.0.8
  - c-blosc2=2.10.5
  - ca-certificates=2023.11.17
  - cffi=1.16.0
  - colorama=0.4.6
  - dataclasses=0.8
  - executing=0.8.3
  - icc_rt=2022.1.0
  - intel-openmp=2023.1.0
  - ipython=8.12.2
  - jedi=0.18.1
  - libffi=3.4.4
  - lz4-c=1.9.4
  - lzo=2.10
  - matplotlib-inline=0.1.6
  - mkl=2023.1.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.8
  - mkl_random=1.2.4
  - numexpr=2.8.4
  - numpy=1.23.5
  - numpy-base=1.23.5
  - openssl=3.0.12
  - packaging=23.1
  - paramiko=2.8.1
  - parso=0.8.3
  - pickleshare=0.7.5
  - pip=23.3
  - portaudio=19.6.0
  - prompt-toolkit=3.0.36
  - pure_eval=0.2.2
  - py-cpuinfo=9.0.0
  - pyaudio=0.2.11
  - pycparser=2.21
  - pygments=2.15.1
  - pynacl=1.5.0
  - python=3.8.18
  - python-sounddevice=0.4.6
  - python_abi=3.8
  - six=1.16.0
  - sqlite=3.41.2
  - stack_data=0.2.0
  - tbb=2021.8.0
  - traitlets=5.7.1
  - typing_extensions=4.7.1
  - vc=14.2
  - vs2015_runtime=14.27.29016
  - wcwidth=0.2.5
  - wheel=0.41.2
  - xz=5.4.2
  - zlib=1.2.13
  - zlib-ng=2.0.7
  - zstd=1.5.5
  - pip:
      - arabic-reshaper==3.0.0
      - astunparse==1.6.3
      - beautifulsoup4==4.12.2
      - blosc2==2.0.0
      - certifi==2023.7.22
      - cffi==1.16.0
      - charset-normalizer==3.3.2
      - contourpy==1.1.1
      - cryptography==41.0.5
      - cycler==0.12.1
      - cython==3.0.5
      - decorator==4.4.2
      - dukpy==0.3.0
      - elementpath==4.1.5
      - esprima==4.0.1
      - et-xmlfile==1.1.0
      - ffpyplayer==4.5.1
      - fonttools==4.44.0
      - freetype-py==2.4.0
      - future==0.18.3
      - gevent==23.9.1
      - gitdb==4.0.11
      - gitpython==3.1.40
      - greenlet==3.0.1
      - html2text==2020.1.16
      - idna==3.4
      - imageio==2.32.0
      - imageio-ffmpeg==0.4.9
      - importlib-resources==6.1.0
      - javascripthon==0.12
      - json-tricks==3.17.3
      - kiwisolver==1.4.5
      - liesl==0.3.5.0
      - markdown-it-py==3.0.0
      - matplotlib==3.7.3
      - mdurl==0.1.2
      - metawear==1.0.8
      - moviepy==1.0.3
      - msgpack==1.0.7
      - msgpack-numpy==0.4.8
      - opencv-python==4.8.1.78
      - openpyxl==3.1.2
      - pandas==2.0.3
      - pillow==10.0.1
      - proglog==0.1.10
      - psutil==5.9.6
      - psychopy==2023.1.2
      - psychtoolbox==3.0.19.0
      - psycopg2==2.9.9
      - pycap==2.6.0
      - pydantic==2.5.2
      - pydantic-core==2.14.5
      - pyglet==1.4.11
      - pylsl==1.16.2
      - pynput==1.7.6
      - pyparallel==0.2.2
      - pyparsing==3.1.1
      - pypi-search==2.0
      - pypiwin32==223
      - pyqt5==5.15.10
      - pyqt5-qt5==5.15.2
      - pyqt5-sip==12.13.0
      - pyrealsense2==2.54.2.5684
      - pyserial==3.5
      - FreeSimpleGUI==5.2.0.post1
      - python-bidi==0.4.2
      - python-dateutil==2.8.2
      - python-gitlab==4.1.1
      - python-vlc==3.0.11115
      - pytz==2023.3.post1
      - pywin32==306
      - pywinhook==1.6.2
      - pyxdf==1.16.4
      - pyyaml==6.0.1
      - pyzmq==25.1.1
      - questplus==2023.1
      - requests==2.31.0
      - requests-toolbelt==1.0.0
      - scipy==1.10.1
      - semantic-version==2.10.0
      - setuptools==66.1.1
      - sk-video==1.1.10
      - smmap==5.0.1
      - soundfile==0.12.1
      - soupsieve==2.5
      - sshtunnel==0.4.0
      - tqdm==4.66.1
      - tzdata==2023.3
      - ujson==5.8.0
      - urllib3==2.0.7
      - warble==1.2.9
      - websockets==12.0
      - wxpython==4.2.1
      - xarray==2023.1.0
      - xmlschema==2.5.0
      - zipp==3.17.0
      - zope-event==5.0
      - zope-interface==6.1
      - git+https://github.com/neurobooth/neurobooth-terra.git#egg=neurobooth_terra
      - h5py==3.10.0
      - h5io==0.2.1
