instruction_id: sacc_horiz_1
instruction_text: null
instruction_filetype: mp4
instruction_file: oculomotor_horizontal_saccades_2022_06_03_v0.6.mp4
arg_parser: iout.stim_param_reader.py::InstructionArgs()
