device_id: Eyelink_1
device_sn: 192.168.100.15
device_name: EYELIN Portable Duo
device_location: '25_19_36'
wearable_bool: false
device_make: SR
device_model: 'EYELINK CL 6.50  '
device_firmware: None
sensor_id_array:
- Eyelink_sens_1
