device_id: Eyelink_demo
device_sn: null
device_name: EYELINK Portable Duo
device_location: '25_19_36'
wearable_bool: false
device_make: SR
device_model: 'EYELINK CL 6.50  '
device_firmware: None
sensor_ids:
- Eyelink_sens_1
arg_parser: iout.stim_param_reader.py::DeviceArgs()
