device_id: Intel_D455_1
device_sn: '037522250727'
device_name: Intel RealSense D455
device_location: '0_0_0'
wearable_bool: false
device_make: Intel RealSense
device_model: D455
device_firmware: 05.13.00.50
sensor_ids:
- Intel_D455_rgb_1
- Intel_D455_depth_1
arg_parser: iout.stim_param_reader.py::DeviceArgs
