device_id: IPhone_dev_1
device_sn: None
device_name: IPhone
wearable_bool: false
device_make: Apple Inc
device_model: '13'
device_firmware: '14.5'
sensor_ids:
- IPhone_sens_1
device_start_function: iout.lsl_streamer.py::start_iphone_stream()
arg_parser: iout.stim_param_reader.py::DeviceArgs()
