device_id: Mbient_BK_1
mac: FE:AB:CF:19:7A:CB
device_name: mbient
device_location: 'Null'
wearable_bool: true
device_make: MbientLab Inc
device_model: MMS
device_firmware: '1.7'
sensor_ids:
- mbient_acc_1
- mbient_gyro_1
arg_parser: iout.stim_param_reader.py::MbientDeviceArgs()
