device_id: Mbient_RH_2
device_sn: C7:94:07:76:8D:6B
device_name: mbient
device_location: 'Null'
wearable_bool: true
device_make: MbientLab Inc
device_model: MMS
device_firmware: '1.7'
sensor_ids:
- mbient_acc_1
- mbient_gyro_1
arg_parser: iout.stim_param_reader.py::DeviceArgs()
