device_id: Mbient_RF_2
device_sn: E5:F6:FB:6D:11:8A
device_name: mbient
device_location: 'Null'
wearable_bool: true
device_make: MbientLab Inc
device_model: MMS
device_firmware: '1.7'
sensor_ids:
- mbient_acc_1
- mbient_gra_1
arg_parser: iout.stim_param_reader.py::DeviceArgs
