device_id: Mouse
device_sn: None
device_name: Mouse
device_location: null
wearable_bool: false
device_make: null
device_model: null
device_firmware: null
sensor_id_array:
- Mouse
arg_parser: iout.stim_param_reader.py::DeviceArgs
