collection_id: demo_calib
is_active: false
session_start_slide: welcome.jpg
session_end_slide: end_slide_01_23_25.jpg
task_ids:
- calibration_obs_1
- finger_nose_demo_obs_1
- mouse_demo_obs
- passage_obs_1
arg_parser: iout.stim_param_reader.py::CollectionArgs()
