collection_id: eyetracker_test
is_active: false
session_start_slide: welcome.jpg
session_end_slide: end_slide_01_23_25.jpg
task_ids:
- calibration_obs_1
- pursuit_test_obs_1
arg_parser: iout.stim_param_reader.py::CollectionArgs()
