collection_id: mvp_030
is_active: false
task_array:
- intro_sess_obs_1
- intro_occulo_obs_1
- calibration_obs_1
- pursuit_obs
- fixation_no_target_obs_1
- gaze_holding_obs_1
- saccades_horizontal_obs_1
- saccades_vertical_obs_1
- intro_cog_obs_1
- MOT_obs_1
- DSC_obs
- hevelius_obs
- intro_speech_obs_1
- passage_obs_1
- ahh_obs_1
- gogogo_obs_1
- lalala_obs_1
- mememe_obs_1
- pataka_obs_1
- coord_pause_obs_1
- finger_nose_obs_1
- foot_tapping_obs_1
- altern_hand_mov_obs_1
- coord_pause_obs_2
- sit_to_stand_obs
arg_parser: iout.stim_param_reader.py::CollectionArgs
