collection_id: no_IMU
is_active: false
session_start_slide: welcome.jpg
session_end_slide: end_slide_01_23_25.jpg
task_ids:
- noIMU_gogogo_obs_1
- noIMU_ahh_obs_1
arg_parser: iout.stim_param_reader.py::CollectionArgs()
