collection_id: testing
is_active: false
session_start_slide: welcome.jpg
session_end_slide: end_slide_01_23_25.jpg
task_ids:
- calibration_obs_1
- saccades_horizontal_obs_1
- timing_test_obs
- clapping_test_obs
arg_parser: iout.stim_param_reader.py::CollectionArgs()
