collection_id: test_no_eyelink
is_active: true
session_start_slide: welcome.jpg
session_end_slide: end_slide_01_23_25.jpg
task_ids:
- intro_sess_obs_1
- gogogo_test_obs_1
- altern_hand_test_obs_1
- foot_tapping_test_obs_1
- sit_to_stand_test_obs
arg_parser: iout.stim_param_reader.py::CollectionArgs()
