- name: Anaconda-Action
  # You may pin to the exact commit or the version.
  # uses: fdiblen/anaconda-action@be27c7e5ae6222eab157d4b4b3c099678de45659
  uses: fdiblen/anaconda-action@0.1.20
  with:
    # Environment name.
    envName: environment-staging.yml # default is environment.yml
    # Environment file name.
    envFileName: environment-staging.yml # default is environment.yml
    # Desired Python version to create a conda environment.
    pythonVersion: 3.6 # optional, default is default
    # Activate the new environment.
    activateEnv: true # optional, default is true